#!/usr/bin/env bash
# This script displays the content of /etc/passwd in a specific format
while IFS=: read -r username _ userid _ _ homedirectory _; do
    echo "$username:$userid:$homedirectory"
done < /etc/passwd
