#!/usr/bin/env bash
# This script displays "Best School" 10 times but on the 4 loop it displays ""bad luck " and on the 8 loop "good luck"
i=0
while [ "$i" -lt 10 ]; do
i=$((i+1))
if [ "$i" -eq 4 ]; then
echo "bad luck"
elif [ "$i" -eq 8 ]; then
echo "good luck"
else
echo "Best School"
fi
done

