#!/usr/bin/env bash
# This script give information about the school file
if [ -e school ]; then 
echo "school file exists"
if [ -f school ]; then
echo "school is a regular file"
else
echo "school file is  empty"
fi
if [ -s school ]; then 
echo "school file is not empty"
fi
else 
echo "school file does not exist"
fi

